--문자열 함수
--LOWER(),INITCAP(),UPPER()
SELECT LOWER('HELLO'), INITCAP('WORLD') FROM DUAL; --DUAL은 가상테이블
SELECT LOWER(FIRST_NAME), INITCAP(FIRST_NAME), UPPER(FIRST_NAME) FROM EMPLOYEES;

--함수는 WHERE절에도 적용됩니다.
SELECT FIRST_NAME FROM EMPLOYEES WHERE UPPER(FIRST_NAME) = 'STEVEN';

--LENGTH() -길이, INSTR() -문자 찾기
SELECT FIRST_NAME, LENGTH(FIRST_NAME), INSTR(FIRST_NAME, 'e') FROM EMPLOYEES;

--SUBSTR() -문자열 자르기, CONCAT() -문자열 합치기
SELECT FIRST_NAME, SUBSTR(FIRST_NAME, 1,3) FROM EMPLOYEES; --1번째에서 3글자를 자름
SELECT FIRST_NAME, CONCAT(FIRST_NAME, LAST_NAME), FIRST_NAME || ' ' || LAST_NAME FROM EMPLOYEES;

--LPAD() -왼쪽 채우기, RPAD() -오른쪽 채우기
SELECT LPAD('HELLO', 10, '*')문자열 FROM DUAL; --10칸 잡고, 왼쪽부터 채움
SELECT LPAD(SALARY,10,'*') FROM EMPLOYEES; 
SELECT RPAD(SALARY, 10, '-')FROM EMPLOYEES;

--LTRIM() -왼쪽 제거, RTRIM() -오른쪽 제거, TRIM() -양쪽 제거
SELECT LTRIM('   HELLO') 제거 FROM DUAL;
SELECT LTRIM(FIRST_NAME, 'A') FROM EMPLOYEES; --첫글자 중 문자 A 제거
SELECT RTRIM('  HELLO   ') RESULT FROM DUAL;
SELECT TRIM(' HELLO ') RESULT FROM DUAL;

--REPLACE() -문자열 변경
SELECT REPLACE('HELLO WORLD','HELLO','BYE') REPLACE FROM DUAL;
SELECT REPLACE('HELLO WORD ~!', ' ' , '') REPLACE FROM DUAL; --모든 공백 제거

--중첩
SELECT REPLACE(REPLACE('HELLO WORD ~!','HELLO', 'BYE')) FROM DUAL;



