--DDL문 CREATE, ALTER, DROP
--오라클 대표 데이터 타입( VARCHAR2- 가변 문장, CHAR-고정 문자, NUMBER -숫자, DATE -날짜)

CREATE TABLE DEPT2(
    DEPT_NO NUMBER(2), --자리수 (정수 2자리)
    DEPT_NAME VARCHAR2(20),-- 최대 20바이트, 가변문자형
    DEPT_YN CHAR(1), -- 1BYTE 고정 문자형
    DEPT_DATE DATE,
    DEPT_BONUS NUMBER(10,3) --10자리, 소수부 3자리
);

DESC DEPT2;
INSERT INTO DEPT2 VALUES(99, 'SALES', 'Y', SYSDATE, 3.14);
INSERT INTO DEPT2 VALUES(98, 'SALES', '홍', SYSDATE, 3.14); --한글은 2바이트, 데이터입력X

SELECT * FROM DEPT2;
COMMIT;

-------------------------------------------------------------------------------
--열추가
ALTER TABLE DEPT2 ADD (DEPT_COUNT NUMBER(3));

SELECT * FROM DEPT2;

--열 이름 변경
ALTER TABLE DEPT2 RENAME COLUMN DEPT_COUNT TO EMP_COUNT;

--열 수정(타입 변경)
ALTER TABLE DEPT2 MODIFY ( EMP_COUNT NUMBER(10) );
DESC DEPT2;

--열 삭제
ALTER TABLE DEPT2 DROP COLUMN EMP_COUNT;

--테이블 삭제
DROP TABLE DEPT2; 
--제약조건 FK도 삭제, 테이블도 삭제 ( 알아만두기.. 쓰면안된다고함)
--DROP TABLE DEPT2 CASCADE 제약조건명;

-------------------------------------------------------------------
--제약조건
--열 레벨 제약 조건(테이블 생성 당시에 열 옆에 적습니다.)
SELECT * FROM USER_CONSTRAINTS;

--제약조건명 없이 키만 지정하면 자동 생성됨
CREATE TABLE DEPTS2(
    DEPT_NO NUMBER(2)        PRIMARY KEY,
    DEPT_NAME VARCHAR2(20)   NOT NULL,
    DEPT_DATE DATE           DEFAULT SYSDATE, --제약조건은아니지만 컬럼의 기본 값 지정
    DEPT_PHONE VARCHAR2(20)  UNIQUE,
    DEPT_BONUS NUMBER(10)    CHECK( DEPT_BONUS > 0 ),
    LOCA NUMBER(4)           REFERENCES LOCATIONS(LOCATION_ID)--FK      
);

DROP TABLE DEPTS2;

--제약 조건명 지정할 때 "CONSTRAINT 제약조건명" ,
CREATE TABLE DEPTS2(
    DEPT_NO NUMBER(2)        CONSTRAINT DEPT2_PK PRIMARY KEY,
    DEPT_NAME VARCHAR2(20)   CONSTRAINT DEPT2_NAME_NN NOT NULL,
    DEPT_DATE DATE           DEFAULT SYSDATE, --제약조건은아니지만 컬럼의 기본 값 지정
    DEPT_PHONE VARCHAR2(20)  CONSTRAINT DEPT2_PHONE_UK UNIQUE,
    DEPT_BONUS NUMBER(10)    CONSTRAINT DEPT2_BONUS_CK CHECK( DEPT_BONUS > 0 ),
    LOCA NUMBER(4)           CONSTRAINT DEPT2_LOCA_FK REFERENCES LOCATIONS(LOCATION_ID)--FK      
);

SELECT * FROM DEPTS2;
DROP TABLE DEPTS2;

--테이블 레벨 제약조건 (슈퍼키나, 다중FK등 선언이 가능)
CREATE TABLE DEPTS2(
    DEPT_NO NUMBER(2),       
    DEPT_NAME VARCHAR2(20)    NOT NULL,
    DEPT_DATE DATE            DEFAULT SYSDATE,
    DEPT_PHONE VARCHAR2(20),  
    DEPT_BONUS NUMBER(10),    
    LOCA NUMBER(4),    
    CONSTRAINT DEPT_PK PRIMARY KEY (DEPT_NO /*,DEPT_NAME*/),
    CONSTRAINT DEPT_PHONE_UK UNIQUE (DEPT_PHONE),
    CONSTRAINT DEPT_BONUS_CK CHECK (DEPT_BONUS > 0),
    CONSTRAINT DEPT_LOCA_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID)
);

DESC DEPTS2;
INSERT INTO DEPTS2 VALUES(10, 'HONG', SYSDATE, '010---', 10000, 1000);
--개체무결성 (NULL과 중복값을 허용하지 않음)
INSERT INTO DEPTS2 VALUES(10, 'HONG', SYSDATE, '010---', 10000, 1000);

--참조무결성 (참조테이블의 PK가 아닌 값이 FK에 들어갈 수 없음)
INSERT INTO DEPTS2 VALUES(20, 'HONG', SYSDATE, '01011111111', 10000, 500); --LOCATION_ID에 500이 없기 때문에 행이 삽입되지 않음.
INSERT INTO DEPTS2 VALUES(20, 'HONG', SYSDATE, '01011111111', 10000, 3200);
--도메인 무결성(값은 컬럼에 정의된 값이어야한다)
INSERT INTO DEPTS2 VALUES(30, 'HONG', SYSDATE, '0102222222' -1000,1000); -- 0보다 작아서 조건에 위배되어 행삽입안됨

-------------------------------------------------------------------------------
-- 제약조건을 추가 OR 삭제
DROP TABLE DEPTS2;

CREATE TABLE DEPTS2(
    DEPT_NO NUMBER(2),        
    DEPT_NAME VARCHAR2(20),   
    DEPT_DATE DATE           DEFAULT SYSDATE, --제약조건은아니지만 컬럼의 기본 값 지정
    DEPT_PHONE VARCHAR2(20),  
    DEPT_BONUS NUMBER(10),    
    LOCA NUMBER(4)
--    CONSTRAINT DEPT_PK PRIMARY KEY (DEPT_NO /*,DEPT_NAME*/),
--    CONSTRAINT DEPT_PHONE_UK UNIQUE (DEPT_PHONE),
--    CONSTRAINT DEPT_BONUS_CK CHECK (DEPT_BONUS > 0),
--    CONSTRAINT DEPT_LOCA_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS(LOCATION_ID)
);

--제약조건은 수정이 없음
ALTER TABLE DEPTS2 ADD CONSTRAINT DEPT_PK PRIMARY KEY (DEPT_NO);
ALTER TABLE DEPTS2 ADD CONSTRAINT DEPT_PHONE_UK UNIQUE (DEPT_PHONE);
ALTER TABLE DEPTS2 ADD CONSTRAINT DEPT_BONUS_CK CHECK (DEPT_BONUS > 0);
ALTER TABLE DEPTS2 ADD CONSTRAINT DEPT_LOCA_FK FOREIGN KEY (LOCA) REFERENCES LOCATIONS (LOCATION_ID);
--NOT NULL은 MODIFY 수정문으로 수정합니다.
ALTER TABLE DEPTS2 MODIFY DEPT_NAME VARCHAR2(20) NOT NULL;

--제약 조건 삭제
ALTER TABLE DEPTS2 DROP CONSTRAINT DEPT_PK;

DROP TABLE DEPTS2;

---------------------------------------------------------------------------------
--연습문제
CREATE TABLE MEMBERS (

    M_NAME VARCHAR2(20) CONSTRAINT NAME_N NOT NULL,
    M_NUM NUMBER(10) CONSTRAINT MEM_MEMNUM_PK PRIMARY KEY,
    REG_DATE DATE DEFAULT SYSDATE,
    GENDER VARCHAR2(10) CONSTRAINT MEM_GENDER_CK CHECK(GENDER = 'M' OR GENDER = 'F'),
    LOCA NUMBER(10) CONSTRAINT MEM_LOCA_LOC_LOCID_FK REFERENCES LOCATIONS(LOCATION_ID)
);

ALTER TABLE MEMBERS MODIFY ( M_NAME VARCHAR2(30) );
ALTER TABLE MEMBERS MODIFY ( GENDER CHAR(1));
ALTER TABLE MEMBERS MODIFY ( REG_DATE UNIQUE);

SELECT * FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'MEMBERS';

INSERT INTO MEMBERS VALUES ('AAA',1,'2018-07-01','M',1800);
INSERT INTO MEMBERS VALUES ('BBB',2,'2018-07-02','F',1900);
INSERT INTO MEMBERS VALUES ('CCC',3,'2018-07-03','M',2000);
INSERT INTO MEMBERS VALUES ('DDD',4,'2023-05-22','M',2000);

SELECT * FROM MEMBERS;

SELECT M_NAME,
       M_NUM,
       L.STREET_ADDRESS,
       L.LOCATION_ID 
FROM MEMBERS M 
INNER JOIN LOCATIONS L 
ON M.LOCA = L.LOCATION_ID 
ORDER BY M_NUM;

COMMIT;
